FROM python:slim-buster

LABEL maintainer="Yusen Zhu yusenz@gatech.edu"
ENV     BASE_DIR="/app"

RUN apt-get -y update && \
    pip install numpy dicom_numpy && \
    pip install -U pip setuptools && \
    pip --no-cache-dir install pydicom nibabel && \
    apt-get update

WORKDIR /app


WORKDIR ${BASE_DIR}
COPY dicom_pypreprocess.py ${BASE_DIR}/
COPY output_randomcsv.py ${BASE_DIR}/
