FROM openjdk:11.0.12-jdk

VOLUME /tmp
ADD target/nexusweb-0.0.1-SNAPSHOT.jar /app.jar
RUN rm -rf /var/cache/apk/* && sh -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

