email: ping.gu@dbmi.emory.edu
label: nexus-distributed-workflows
dataInput: /labs/mahmoudilab/dicom2nifti/input_dicom/poc_test_input.txt
taskList:
  - name: taskA
    index: 0
    preemptibleOption: PREEMPTIBLE_STANDARD_ATTEMPT_BOTH
    project: nexus-bmi
    runningHoursAllowed: 2
    workflowType: WDL
    wdlFilePath: 'DB:poc_taskA_wdl'
    inputFilePath: 'DB:poc_taskA_json'
  - name: taskB
    index: 1
    preemptibleOption: PREEMPTIBLE_STANDARD_ATTEMPT_BOTH
    project: cloudypipelines
    runningHoursAllowed: 2
    workflowType: WDL
    wdlFilePath: 'DB:poc_taskB_wdl'
    inputFilePath: 'DB:poc_taskB_json'
  - name: taskC
    index: 2
    preemptibleOption: PREEMPTIBLE_STANDARD_ATTEMPT_BOTH
    project: nexus-bmi
    runningHoursAllowed: 2
    workflowType: WDL
    wdlFilePath: 'DB:poc_taskC_wdl'
    inputFilePath: 'DB:poc_taskC_json'

